version: "3.9"

services:
  app:
    build: .
    container_name: rails_app
    depends_on:
      - db
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    command: ["rails", "server", "-b", "0.0.0.0"]

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pg_data:
